<?php

/**
 * @file
 * Hook implementations for anytown module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function anytown_help($route_name, RouteMatchInterface $route_match) {
  // Primary help page for the module will be at "help.page.$modulename".
  if ($route_name === 'help.page.anytown') {
    // Example of accessing a service via a hook, where you can't perform
    // dependency injection.
    /** @var \Drupal\Core\Session\AccountProxyInterface $current_user */
    $current_user = \Drupal::service('current_user');

    return '<p>' . t("Hi %name, the anytown module provides code specific to the Anytown Farmer's market website. This includes the weather forecast page, block, and related settings.", ['%name' => $current_user->getDisplayName()]) . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function anytown_theme() {
  return [
    'weather_page' => [
      'variables' => [
        'weather_intro' => '',
        'weather_forecast' => '',
        'short_forecast' => '',
        'weather_closures' => '',
      ],
    ],
  ];
}